conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
	path('', views.index, name="inbox"),
	path('<int:pk>/', views.detail, name="detail"),
	path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
	path('', views.indexInfo, name="indexInfo"),
	path('indexInfo/', views.index, name="index"),
	path('contact/', views.contact, name="contact"),
	path('signup/', views.signup, name="signup"),
	path('login/', auth_views.LoginView.as_view(template_name='core/login.html' ,authentication_form=LoginForm), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
	path('', views.index, name="index"),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
	path('', views.items, name="items"),
	path('new/', views.new, name="new"),
	path('<int:pk>/', views.detail, name="detail"),
	path('<int:pk>/delete/', views.delete, name="delete"),
	path('<int:pk>/edit/', views.edit, name="edit"),

]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from core.views import index, contact

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):

	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))


class SignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

	#Here we will style and fix the fields:

	username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder': 'Your email',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	password1 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

	password2 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Repeat your password',
		'class': 'w-full py-4 px-6 rounded-xl'
	}))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm

# Create your views here.

def indexInfo(request):
	items = Item.objects.filter(is_sold=False)[0:6]
	categories = Category.objects.all()

	return render(request, "core/indexInfo.html", {
		"categories": categories,
		"items": items,
	})


def index(request):
	items = Item.objects.filter(is_sold=False)[0:6]
	categories = Category.objects.all()

	return render(request, "core/index.html", {
		"categories": categories,
		"items": items,

	})

def contact(request):
	return render(request, "core/contact.html")

def signup(request):
	
	if request.method == "POST":
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form
	})

core/templates/core/base.html
<!DOCTYPE html>
	<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<script src="https://cdn.tailwindcss.com"></script>

		<title>{% block title %}{% endblock %} | Puddle</title>

		<style>
			  .circles{
				position: absolute;
				top: 0;
				left: 0;
				width: 100%;
				height: 100%;
				overflow: hidden;
			}
			.circles li{
				position: absolute;
				display: block;
				list-style: none;
				width: 20px;
				height: 20px;
				background: rgba(255, 255, 255, 0.2);
				animation: animate 25s linear infinite;
				bottom: -150px;  
			}
			.circles li:nth-child(1){
				left: 25%;
				width: 80px;
				height: 80px;
				animation-delay: 0s;
			}
			
			
			.circles li:nth-child(2){
				left: 10%;
				width: 20px;
				height: 20px;
				animation-delay: 2s;
				animation-duration: 12s;
			}
			
			.circles li:nth-child(3){
				left: 70%;
				width: 20px;
				height: 20px;
				animation-delay: 4s;
			}
			
			.circles li:nth-child(4){
				left: 40%;
				width: 60px;
				height: 60px;
				animation-delay: 0s;
				animation-duration: 18s;
			}
			
			.circles li:nth-child(5){
				left: 65%;
				width: 20px;
				height: 20px;
				animation-delay: 0s;
			}
			
			.circles li:nth-child(6){
				left: 75%;
				width: 110px;
				height: 110px;
				animation-delay: 3s;
			}
			
			.circles li:nth-child(7){
				left: 35%;
				width: 150px;
				height: 150px;
				animation-delay: 7s;
			}
			
			.circles li:nth-child(8){
				left: 50%;
				width: 25px;
				height: 25px;
				animation-delay: 15s;
				animation-duration: 45s;
			}
			
			.circles li:nth-child(9){
				left: 20%;
				width: 15px;
				height: 15px;
				animation-delay: 2s;
				animation-duration: 35s;
			}
			
			.circles li:nth-child(10){
				left: 85%;
				width: 150px;
				height: 150px;
				animation-delay: 0s;
				animation-duration: 11s;
			}
			@keyframes animate {
			
				0%{
					transform: translateY(0) rotate(0deg);
					opacity: 1;
					border-radius: 0;
				}
			
				100%{
					transform: translateY(-1000px) rotate(720deg);
					opacity: 0;
					border-radius: 50%;
				}
			
			}
			.triangle{
			border-top:60rem solid #fff;
			border-left:25rem solid transparent;
			}
		</style>
	</head>
	<body>
		<nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
			<a href="/" class="text-xl font-semibold">Puddle</a>

			<div class="space-x-6">
				<a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
				<a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Broswe</a>

				{% if request.user.is_authenticated %}
					<a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
					<a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
					<!-- <a href="{% url 'core:logout' %}" method="post" class="text-lg font-semibold hover:text-gray-500">Logout</a> -->
					<form id="logoutForm" action="{% url 'core:logout' %}" method="post" style="display: none;">
						{% csrf_token %}
					</form>
					<a href="#" onclick="document.getElementById('logoutForm').submit(); return false;" class="text-lg font-semibold hover:text-gray-500">Logout</a>
					
				{% else %}
					<a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
					<a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log In</a>
				{% endif %}
			</div>
		</nav>

		<div class="px-6 py-6">
			{% block content %}
			{% endblock %}
		</div>

		<footer class="py-6 px-6 flex justify-between bg-gray-800">
			<div class="w-2/3 pr-10">
				<h3 class="mb-5 text-gray-400 font-semibold">About</h3>

				<p class="text-lg text-gray-500">Lorem ipsum Lorem ipsumLorem ipsum Lorem ipsum</p>
			</div>
			<div class="w-1/3">
				<h3 class="mb-5 text-gray-400 font-semibold">Menu</h3>

				<ul class="space-y-2">
					<li>
						<a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a>
					</li>
					<li>
						<a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
					</li>
					<li>
						<a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a>
					</li>
				</ul>
			</div>
		</footer>
	</body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
	<h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
	<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class="mb-12 text-2xl text-center">Newest items</h2>

		<div class="grid grid-cols-3 gap-3">
			{% for item in items %}
				<div>
					<a href="{% url 'item:detail' item.id %}">
						<div>
							<img src="{{ item.image.url }}" class="rounded-t-xl" />
						</div>

						<div class="p-6 bg-white rounded-b-xl">
							<h2 class="text-2xl">{{ item.name }}</h2>
							<p class="text-gray-500">Price: {{ item.price }}</p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>

	<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class="mb-12 text-2xl text-center">Categories</h2>

		<div class="grid grid-cols-3 gap-3">
			{% for category in categories %}
				<div>
					<a href="#">

						<div class="p-6 bg-white rounded-b-xl">
							<h2 class="text-2xl">{{ category.name }}</h2>
							<p class="text-gray-500">{{ category.items.count }} items</p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>


{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="relative min-h-screen flex">
    <div class="flex flex-col sm:flex-row items-center md:items-start sm:justify-center md:justify-start flex-auto min-w-0 bg-white">
        <div class="sm:w-1/2 xl:w-2/5 h-full hidden md:flex flex-auto items-center justify-start p-10 overflow-hidden bg-purple-900 text-white bg-no-repeat bg-cover relative" style="background-image: url(https://images.unsplash.com/photo-1579451861283-a2239070aaa9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80);">
            <div class="absolute bg-gradient-to-b from-blue-900 to-gray-900 opacity-75 inset-0 z-0"></div>
            <div class="absolute triangle  min-h-screen right-0 w-16" style=""></div>
            <a href="https://codepen.io/uidesignhub" target="_blank" title="codepen aji" class="flex absolute top-5 text-center text-gray-100 focus:outline-none">
                <img src="/storage/avatars/njkIbPhyZCftc4g9XbMWwVsa7aGVPajYLRXhEeoo.jpg" alt="aji" class="object-cover mx-auto w-8 h-8 rounded-full w-10 h-10">
                <p class="text-xl ml-3">aji<strong>mon</strong></p>
            </a>
            <img src="https://jasper-pimstorage-skullcandy.s3.us-west-1.amazonaws.com/bd2253a9671dac36a95faf821b52e78935050140be1718ce001f6aace45cf25c.png" class="h-96 absolute right-5 mr-5">
            <div class="w-full  max-w-md z-10">
                <div class="sm:text-4xl xl:text-5xl font-bold leading-tight mb-6">Reference site about Lorem Ipsum..</div>
                <div class="sm:text-sm xl:text-md text-gray-200 font-normal"> What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?</div>
            </div>
            <!---remove custom style-->
            <ul class="circles">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div class="md:flex md:items-center md:justify-center w-full sm:w-auto md:h-full w-2/5 xl:w-2/5 p-8 md:p-10 lg:p-14 sm:rounded-lg md:rounded-none bg-white ">
            <div class="max-w-md w-full space-y-8">
                <div class="text-center">
                    <h2 class="mt-6 text-3xl font-bold text-gray-900">
                        Welcome Back!
                    </h2>
                    <p class="mt-2 text-sm text-gray-500">Please sign in to your account</p>
                </div>
                <form class="mt-8 space-y-6" action="#" method="POST">
                    {% csrf_token %}
                    <div class="relative">
                        <div class="absolute right-3 mt-4">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                        </div>
                        <label class="ml-3 text-sm font-bold text-gray-700 tracking-wide">Username</label>
                        <input class="w-full text-base px-4 py-2 border-b border-gray-300 focus:outline-none rounded-2xl focus:border-indigo-500" type="text" name="username" placeholder="Username" required>
                    </div>
                    <div class="mt-8 content-center">
                        <label class="ml-3 text-sm font-bold text-gray-700 tracking-wide">
                            Password
                        </label>
                        <input class="w-full content-center text-base px-4 py-2 border-b rounded-2xl border-gray-300 focus:outline-none focus:border-indigo-500" type="password" name="password" placeholder="Enter your password" required>
                    </div>
                    <div class="flex items-center justify-between">
                        <div class="flex items-center">
                            <input id="remember_me" name="remember_me" type="checkbox" class="h-4 w-4 bg-blue-500 focus:ring-blue-400 border-gray-300 rounded">
                            <label for="remember_me" class="ml-2 block text-sm text-gray-900">
                                Remember me
                            </label>
                        </div>
                        <div class="text-sm">
                            <a href="#" class="text-indigo-400 hover:text-blue-500">
                                Forgot your password?
                            </a>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="w-full flex justify-center bg-gradient-to-r from-indigo-500 to-blue-600  hover:bg-gradient-to-l hover:from-blue-500 hover:to-indigo-600 text-gray-100 p-4  rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-500">
                            Sign in
                        </button>
                    </div>
                    <p class="flex flex-col items-center justify-center mt-10 text-center text-md text-gray-500">
                        <span>Don't have an account?</span>
                        <a href="#" class="text-indigo-400 hover:text-blue-500 no-underline hover:underline cursor-pointer transition ease-in duration-300">Sign up</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="relative min-h-screen flex">
    <div class="flex flex-col sm:flex-row items-center md:items-start sm:justify-center md:justify-start flex-auto min-w-0 bg-white">
        <div class="sm:w-1/2 xl:w-2/5 h-full hidden md:flex flex-auto items-center justify-start p-10 overflow-hidden bg-purple-900 text-white bg-no-repeat bg-cover relative" style="background-image: url(https://images.unsplash.com/photo-1579451861283-a2239070aaa9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1950&amp;q=80);">
            <div class="absolute bg-gradient-to-b from-blue-900 to-gray-900 opacity-75 inset-0 z-0"></div>
            <div class="absolute triangle  min-h-screen right-0 w-16" style=""></div>
            <a href="https://codepen.io/uidesignhub" target="_blank" title="codepen aji" class="flex absolute top-5 text-center text-gray-100 focus:outline-none">
                <img src="/storage/avatars/njkIbPhyZCftc4g9XbMWwVsa7aGVPajYLRXhEeoo.jpg" alt="aji" class="object-cover mx-auto w-8 h-8 rounded-full w-10 h-10">
                <p class="text-xl ml-3">aji<strong>mon</strong></p>
            </a>
            <img src="https://jasper-pimstorage-skullcandy.s3.us-west-1.amazonaws.com/bd2253a9671dac36a95faf821b52e78935050140be1718ce001f6aace45cf25c.png" class="h-96 absolute right-5 mr-5">
            <div class="w-full  max-w-md z-10">
                <div class="sm:text-4xl xl:text-5xl font-bold leading-tight mb-6">Reference site about Lorem Ipsum..</div>
                <div class="sm:text-sm xl:text-md text-gray-200 font-normal"> What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book it has?</div>
            </div>
            <!---remove custom style-->
            <ul class="circles">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div class="md:flex md:items-center md:justify-center w-full sm:w-auto md:h-full w-2/5 xl:w-2/5 p-8 md:p-10 lg:p-14 sm:rounded-lg md:rounded-none bg-white ">
            <div class="max-w-md w-full space-y-8">
                <div class="text-center">
                    <h2 class="mt-6 text-3xl font-bold text-gray-900">
                        Sign Up
                    </h2>
                    <p class="mt-2 text-sm text-gray-500">Please sign up to create an account</p>
                </div>
                <form class="mt-8 space-y-6" action="#" method="POST">
                    {% csrf_token %}
                    <div class="relative">
                        <div class="absolute right-3 mt-4">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                        </div>
                        <label class="ml-3 text-sm font-bold text-gray-700 tracking-wide">Username</label>
                        <input class="w-full text-base px-4 py-2 border-b border-gray-300 focus:outline-none rounded-2xl focus:border-indigo-500" type="text" name="username" placeholder="Username" required>
                    </div>
                    <div class="relative">
                        <div class="absolute right-3 mt-4">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                        </div>
                        <label class="ml-3 text-sm font-bold text-gray-700 tracking-wide">Email</label>
                        <input class="w-full text-base px-4 py-2 border-b border-gray-300 focus:outline-none rounded-2xl focus:border-indigo-500" type="email" name="email" placeholder="mail@gmail.com" required>
                    </div>
                    <div class="mt-8 content-center">
                        <label class="ml-3 text-sm font-bold text-gray-700 tracking-wide">
                            Password
                        </label>
                        <input class="w-full content-center text-base px-4 py-2 border-b rounded-2xl border-gray-300 focus:outline-none focus:border-indigo-500" type="password" name="password1" placeholder="Enter your password" required>
                    </div>
                    <div class="mt-8 content-center">
                        <label class="ml-3 text-sm font-bold text-gray-700 tracking-wide">
                            Repeat Password
                        </label>
                        <input class="w-full content-center text-base px-4 py-2 border-b rounded-2xl border-gray-300 focus:outline-none focus:border-indigo-500" type="password" name="password2" placeholder="Repeat your password" required>
                    </div>
                    <div>
                        <button type="submit" class="w-full flex justify-center bg-gradient-to-r from-indigo-500 to-blue-600  hover:bg-gradient-to-l hover:from-blue-500 hover:to-indigo-600 text-gray-100 p-4  rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-500">
                            Sign up
                        </button>
                    </div>
                    <p class="flex flex-col items-center justify-center mt-10 text-center text-md text-gray-500">
                        <span>Already have an account?</span>
                        <a href="#" class="text-indigo-400 hover:text-blue-500 no-underline hover:underline cursor-pointer transition ease-in duration-300">Sign in</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}